language: python
env:
- SERVER_IP_ADDRESS=182.253.108.28
jobs:
  include:
  - stage: build
    name: Build to Docker Hub
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t sdbayes .
    - docker images
    - docker tag sdbayes $DOCKER_USERNAME/sdbayes
    - docker push $DOCKER_USERNAME/sdbayes
  - stage: deploy
    name: Deploy to Production
    script:
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS mkdir -p $DIR
    - scp -r docker-compose.prod.yml $SSH_USER@$SERVER_IP_ADDRESS:$DIR
    - scp -r prod.env $SSH_USER@$SERVER_IP_ADDRESS:$DIR
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS docker volume rm sdbayes_sdbayes_data
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS docker-compose -f $DIR/docker-compose.prod.yml rm -f
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS docker-compose -f $DIR/docker-compose.prod.yml pull
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS docker-compose -f $DIR/docker-compose.prod.yml up --build -d

before_install:
- openssl aes-256-cbc -K $encrypted_117718da09e6_key -iv $encrypted_117718da09e6_iv -in prod.env.enc -out prod.env -d
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS pwd
