language: python #can be any language, just php for example

services:
  - docker # required, but travis uses older version of docker :(

before_install:
    - docker build -t carlad/sinatra .

deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
      branch: develop