language: python #can be any language, just php for example

services:
  - docker # required, but travis uses older version of docker :(

build:
  - docker --version  # document the version travis is using
  - docker build -t sdbayes .

# deploy:
#     provider: script
#     script: bash scripts/deploy.sh
#     on:
#       branch: develop