jobs:
    include:
      - stage: build docker image
        script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t sdbayes .
        - docker images
        - docker tag sdbayes $DOCKER_USERNAME/sdbayes
        - docker push $DOCKER_USERNAME/sdbayes
