language: python
env:
- SERVER_IP_ADDRESS=182.253.108.28

jobs:
  include:
  - stage: deploy
    name: Deploy to Production
    script:
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS mkdir -p $DIR
    - scp -r docker-compose.prod.yml $SSH_USER@$SERVER_IP_ADDRESS:$DIR
    - ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS docker-compose -f $DIR/docker-compose.prod.yml
      up -d --build
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $SSH_USER@$SERVER_IP_ADDRESS pwd
