
env:
    - SERVER_IP_ADDRESS=182.253.108.28

jobs:
    include:
        - stage: build
          name: "Build image and push to docker hub"
          script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t sdbayes .
          - docker images
          - docker tag sdbayes $DOCKER_USERNAME/sdbayes
          - docker push $DOCKER_USERNAME/sdbayes
        - stage: deploy
          name: "Deploy to Production"
          before_script:
            - openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out ./deploy_key -d
            - eval "$(ssh-agent -s)"
            - chmod 600 ./deploy_key
            - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            - ssh-add ./deploy_key
          script:
            - docker-compose -f docker-compose.prod.yml up web -d
            - echo -e "Done."

