version: "3.7"
services:
  web:
    restart: unless-stopped
    container_name: sdbayes
    image: bararamadhan/sdbayes:latest
    env_file:
      - prod.env
    volumes:
      - sdbayes_data:/usr/src/run
    links:
      - db
      - redis
    command: gunicorn --bind 0.0.0.0:5001 manage:app -w 2 --threads 2
    ports:
      - 5001:5001
    expose:
      - 5001
    depends_on:
      - db
      - redis
    networks:
      - local

  db:
    container_name: sdbayes-postgres
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - prod.env
    networks:
      - local

  worker:
    container_name: sdbayes-worker
    image: bararamadhan/sdbayes:latest
    restart: unless-stopped
    env_file:
      - prod.env
    command: python manage.py run_worker
    volumes:
      - sdbayes_data:/usr/src/run
    depends_on:
      - redis
      - db
    networks:
      - local

  redis:
    restart: unless-stopped
    container_name: "sdbayes-redis"
    image: "redis:latest"
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  sdbayes_data:
  postgres_data:
  redis_data:
