version: "3.7"

services:
  sdbayes_web:
    restart: always
    container_name: sdbayes
    image: sdbayes_web
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_CONFIG=development
      - SECRET_KEY=INISANGATRAHASIA!
      - APP_NAME=Dev.
      - POSTGRES_URL=sdbayes-postgres
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
      - POSTGRES_DB=sdbayes-development
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_USERNAME=apps@bara.my.id
      - MAIL_PASSWORD=Alhamdulillah
      - TZ=Asia/Jakarta
    links:
      - sdayes-postgres
      - redis
    command: python manage.py runserver -h 0.0.0.0
    depends_on:
      - sdayes-postgres
      - redis
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.entryPoints=https"
      - "traefik.enable=true"
      - "traefik.weight=10"
      - "traefik.frontend.rule=Host:sdbayes.docker.localhost"
      - "traefik.backend=sdbayes-localhost"
    networks:
      - sdbayes_network

  worker:
    restart: always
    image: sdbayes_web
    build:
      context: .
    container_name: sdbayes-worker
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=INISANGATRAHASIA!
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_USERNAME=apps@bara.my.id
      - MAIL_PASSWORD=Alhamdulillah
      - TZ=Asia/Jakarta
    command: python manage.py run_worker
    depends_on:
      - redis
      - sdayes-postgres
    networks:
      - sdbayes_network

  sdayes-postgres:
    restart: always
    container_name: sdbayes-postgres
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_URL=sdbayes-postgres
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
      - POSTGRES_DB=sdbayes-development
      - TZ=Asia/Jakarta
    ports:
      - 5432:5432
    networks:
      - sdbayes_network
  
  adminer:
    image: adminer
    restart: always
    links:
      - sdayes-postgres
    depends_on:
      - sdayes-postgres
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=https"
      - "traefik.enable=true"
      - "traefik.weight=10"
      - "traefik.frontend.rule=Host:adminer.docker.localhost"
      - "traefik.backend=adminer-localhost"
    networks:
      - sdbayes_network


  redis:
    restart: always
    container_name: "sdbayes-redis"
    image: "redis:5.0"
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - sdbayes_network

  monitor:
    build: ./monitor
    image: sdbayes-monitor
    container_name: sdbayes-monitor
    volumes:
      - .:/app
    command: rq-dashboard -H redis
    depends_on:
      - redis
    labels:
      - "traefik.port=9181"
      - "traefik.frontend.entryPoints=https"
      - "traefik.enable=true"
      - "traefik.weight=10"
      - "traefik.frontend.rule=Host:monitor.docker.localhost"
      - "traefik.backend=monitor-localhost"
    networks:
      - sdbayes_network

volumes:
  postgres_data:
  redis_data:

networks:
  sdbayes_network:
    name: sdbayes-local
    driver: bridge
    external: true