version: "3.7"

services:
  sdbayes_web:
    restart: always
    container_name: sdbayes
    image: bararamadhan/sdbayes:latest
    volumes:
      - .:/usr/src/app
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.enable=true"
      - "traefik.weight=10"
      - "traefik.frontend.rule=Host:sdbayes.docker.localhost" # Modify sub-domain with your project or preferred name.
      - "traefik.backend=sdbayes-localhost" # Define a backend name. Must be unique.
      - "traefik.port=5000"
    environment:
      - FLASK_CONFIG=development
      - SECRET_KEY=INISANGATRAHASIA!
      - APP_NAME=Dev.
      - POSTGRES_URL=sdbayes-postgres
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
      - POSTGRES_DB=sdbayes-development
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_USERNAME=apps@bara.my.id
      - MAIL_PASSWORD=Alhamdulillah
      - TZ=Asia/Jakarta
    links:
      - db
      - redis
    expose:
      - 5000
    command: python manage.py runserver -h 0.0.0.0
    depends_on:
      - db
      - redis
    networks:
      - sdbayes_network

  worker:
    restart: always
    image: bararamadhan/sdbayes:latest
    container_name: sdbayes-worker
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=INISANGATRAHASIA!
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_USERNAME=apps@bara.my.id
      - MAIL_PASSWORD=Alhamdulillah
      - TZ=Asia/Jakarta
    command: python manage.py run_worker
    depends_on:
      - redis
      - db
    networks:
      - sdbayes_network

  db:
    restart: always
    container_name: sdbayes-postgres
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_URL=sdbayes-postgres
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
      - POSTGRES_DB=sdbayes-development
      - TZ=Asia/Jakarta
    ports:
      - 5432:5432
    networks:
      - sdbayes_network

  redis:
    restart: always
    container_name: "sdbayes-redis"
    image: "redis:5.0"
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - sdbayes_network

  monitor:
    build: ./monitor
    image: sdbayes-monitor
    container_name: sdbayes-monitor
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.enable=true"
      - "traefik.weight=10"
      - "traefik.frontend.rule=Host:monitor.docker.localhost" # Modify sub-domain with your project or preferred name.
      - "traefik.backend=sdbayes-monitor" # Define a backend name. Must be unique.
      - "traefik.port=9181"
    volumes:
      - .:/app
    expose:
      - 9181
    command: rq-dashboard -H redis
    depends_on:
      - redis
    networks:
      - sdbayes_network

networks:
  sdbayes_network:
    name: sdbayes-local
    driver: bridge
    external: true

volumes:
  postgres_data:
  redis_data:
